import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import Link from 'next/link';

const Home: NextPage = () => {
	const [input, setInput] = useState('');

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<input
					type="text"
					value={input}
					onChange={(e) => setInput(e.target.value)}
				/>
				<button>
					<Link href={`http://localhost:3000/api/${input}`}>Click Me!</Link>
				</button>
			</main>
		</div>
	);
};

export default Home;
