import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
	function fuckYou() {
		alert('Fuck You!');
	}
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<button onClick={() => alert('Fuck You!')}>Click Me!</button>
			</main>
		</div>
	);
};

export default Home;
